### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hotklou2404** [3ddelano/godot-editor-discord-presence#2] opened 2022-01-10 12:04 UTC
**Bug Description**
I installed the plugin through the Godot Editor's AssetLib and let it do an automatic installation to my addons folder.
 But any time I try to activate the plugin it just gives me a warning and an error in the Output log and deactivates.

Sometimes the plugin works while you have the editor open and have just activated it, only to deactivate itself when you open up the editor again at a later time after having closed it. And sometimes after having opened and closed the editor enough times it will just not even activate at all anymore, giving the error as soon as you try to activate it.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Install the plugin (let it do the manual installation from the Godot Editor's AssetLib).
2. Activate the plugin (in "Plugins...").

**Expected Result**
I expect that the plugin should activate and do its thing.

**Actual Result**
I get a warning notification (see the first attached screenshot) and the plugin is deactivated, and in the output log I get this error (see second attached screenshot):
> * res://addons/godot_editor_discord_presence/plugin.gd:37 - Parse Error: The identifier "DiscordRPC" isn't a valid type (not a script or class), or couldn't be found on base "self".
> * modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR

**Screenshots**
![image](https://user-images.githubusercontent.com/72917600/148761882-d5763493-5615-4e24-b723-c2c9091c5906.png)
![image](https://user-images.githubusercontent.com/72917600/148762684-3cfddca3-3f04-42c2-8777-d45b464af219.png)

**Operating System, Godot Version and Plugin Version:**
 - OS: Windows 10
 - Plugin Version: 1.1.0
 - Godot Version:  3.4.2

## Checklist

- [ X ] I have checked for duplicate issues.
- [ X ] I have provided a detailed description of the issue.
- [ X ] I have provided reproduction steps (if applicable).

**Comment by 3ddelano** [comment] 2022-01-11 06:46
I'm unable to reproduce the bug.
I made a new project and installed the plugin from AssetLib everything works as expected on Godot 3.4.2.stable.
Closing and opening the plugin gives no errors and doesnt disable it.

**Comment by Hotklou2404** [comment] 2022-01-13 09:57
> I'm unable to reproduce the bug. I made a new project and installed the plugin from AssetLib everything works as expected on Godot 3.4.2.stable. Closing and opening the plugin gives no errors and doesnt disable it.

Very weird. I also have this same issue with many other plugins, but I can't seem to find any logical cause for so many plugins to be giving issues...

**Comment by 3ddelano** [comment] 2022-01-23 09:18
Closing since non-reproducible. Open it again if needed.

**Closed as completed by 3ddelano** 2022-01-23 09:18 UTC
Labels: bug

**Comment by AutumnRivers** [comment] 2022-02-04 00:54
I know this is closed, but I can confirm I am experiencing this too. On Godot 3.4.2

**Comment by 3ddelano** [comment] 2022-02-04 03:52
Can you send some error logs which hints at the underlying issue. It may show up is you enable verbose mode in the Godot editor settings.

**Comment by AutumnRivers** [comment] 2022-02-04 21:45
Sorry for such a late response! It worked after I came back to my computer the next day, but thank you for replying!
